#include<iostream>
#include<Windows.h>
using namespace std;

void textColor(int font, int background) {
	int color = font + background*16;
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color);
}

int main() {
	textColor(10, 10);	//1
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□□□□□□□□□□□□□□□□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□";	//2
	textColor(0, 0);
	cout << "□□□□□□□□□□□□□□□□□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□";	//3
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□";	//4
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□□□";	//5
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(7, 7);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□";	//6
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(7, 7);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□□□□□";	//7
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(7, 7);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□□□";	//8
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(7, 7);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□□□□□□□";	//9
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(7, 7);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";
	cout << "□□□□□□□□□□";	//10
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(7, 7);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";

	cout << "□□□□□□□□";	//11
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□";
	textColor(9, 9);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";
	cout << "□□□□□□□□";	//12
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□";
	textColor(9, 9);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";

	cout << "□□□□□□";	//13
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□□□";
	textColor(9, 9);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";
	cout << "□□□□□□";	//14
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□□□";
	textColor(9, 9);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";
	cout << "□□□□";	//15
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□" << endl;
	cout << "□□□□";	// 16
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□";	//17
	textColor(0, 0);
	cout << "□□□□□□□□□□□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□";	//18
	textColor(0, 0);
	cout << "□□□□□□□□□□□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□□□□□□□";	// 19
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";
	cout << "□□□□□□□□□□";	// 20
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";

	cout << "□□□□□□□□";	// 21
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□□□";	// 22
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□□□";	// 23
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□";	// 24
	textColor(0, 0);
	cout << "□□";
	textColor(9, 9);
	cout << "□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□";	// 25
	textColor(0, 0);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□\n";
	cout << "□□□□";	// 26
	textColor(0, 0);
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□\n";

	cout << "□□□□□□□□□□□□□□□□□□";	// 27
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□□□□□□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";	// 28
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□□□□□□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□\n";

	cout << "□□□□□□□□□□□□□□□□";	// 29
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□";	// 30
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□□□□□□□□□□□";	// 31
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□";	// 32
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";

	cout << "□□□□□□□□□□□□□□";		// 33
	textColor(0, 0);
	cout << "□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□";	// 34
	textColor(0, 0);
	cout << "□□□□";
	textColor(15, 15);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(15, 15);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(9, 9);
	cout << "□□";
	textColor(0, 0);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(12, 12);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(12, 12);
	cout << "□□□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(12, 12);
	cout << "□□□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(12, 12);
	cout << "□□□□";
	textColor(15, 15);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(10, 10);
	cout << "□□□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□□□";
	textColor(15, 15);
	cout << "□□";
	textColor(12, 12);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(12, 12);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□□□";
	textColor(15, 15);
	cout << "□□";
	textColor(12, 12);
	cout << "□□";
	textColor(0, 0);
	cout << "□□□□";
	textColor(12, 12);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□";
	textColor(15, 15);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□";
	textColor(15, 15);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(12, 12);
	cout << "□□□□□□";
	textColor(0, 0);
	cout << "□□";
	textColor(10, 10);
	cout << "□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□□□□□□□□□□□□□□□□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□\n";
	cout << "□□□□□□□□□□□□□□□□□□";
	textColor(0, 0);
	cout << "□□□□□□□□□□□□□□□□□□□□□□□□□□";
	textColor(10, 10);
	cout << "□□□□□□\n";
	textColor(15, 0);
}